# Generated by Django 4.0 on 2021-12-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı mı?'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Görev'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Ders')),
                ('description', models.TextField(verbose_name='İçerik')),
                ('due', models.DateTimeField(verbose_name='Son Tarih')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
