# Generated by Django 4.0 on 2021-12-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0002_alter_todo_is_finished_alter_todo_title_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exammarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Ders')),
                ('firstExam', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Birinci Vize')),
                ('secondExam', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İkinci Vize')),
                ('final', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Final')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
