# Generated by Django 4.0 on 2021-12-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_exammarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammarks',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ortalama'),
        ),
    ]
