# Generated by Django 4.0 on 2021-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_exammarks_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarks',
            name='average',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='Ortalama'),
        ),
    ]
