# Generated by Django 4.0 on 2021-12-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_exammarks_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarks',
            name='average',
            field=models.FloatField(default=60.0, verbose_name='Ortalama'),
        ),
        migrations.AlterField(
            model_name='exammarks',
            name='final',
            field=models.FloatField(default=0.0, verbose_name='Final'),
        ),
        migrations.AlterField(
            model_name='exammarks',
            name='firstExam',
            field=models.FloatField(default=0.0, verbose_name='Birinci Vize'),
        ),
        migrations.AlterField(
            model_name='exammarks',
            name='secondExam',
            field=models.FloatField(default=0.0, verbose_name='İkinci Vize'),
        ),
    ]
