# Generated by Django 4.0 on 2021-12-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_exammarks_average_alter_exammarks_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarks',
            name='average',
            field=models.FloatField(default=0.0, verbose_name='Ortalama'),
        ),
    ]
