# Generated by Django 4.0 on 2021-12-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_exammarks_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammarks',
            name='average',
            field=models.IntegerField(default=0, verbose_name='Ortalama'),
        ),
    ]
